import { jsPDF } from 'jspdf';
import { ScanResultData } from './scanner';

export async function generateComplianceReport(scanData: ScanResultData): Promise<Buffer> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Title
  doc.setFontSize(22);
  doc.setTextColor(26, 54, 93); // #1a365d
  doc.text('Data Privacy & Security', pageWidth / 2, y, { align: 'center' });
  y += 10;
  doc.text('Threat Assessment', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // ── Target Info
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104); // #4a5568
  doc.text(`Target Website: ${scanData.url}`, pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.text(`Scan Date: ${new Date(scanData.timestamp).toLocaleString()}`, pageWidth / 2, y, { align: 'center' });
  y += 14;

  // ── Grade & Score
  doc.setFontSize(18);
  doc.setTextColor(45, 55, 72); // #2d3748
  doc.text(`Security Grade: ${scanData.grade}`, 20, y);
  y += 8;
  doc.setFontSize(13);
  doc.setTextColor(74, 85, 104);
  doc.text(`Overall Compliance Score: ${scanData.score}%`, 20, y);
  y += 14;

  // ── Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // ── GPC Section
  doc.setFontSize(15);
  doc.setTextColor(45, 55, 72);
  doc.text('Global Privacy Control (GPC) Compliance', 20, y);
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(scanData.gpc.supported ? 56 : 229, scanData.gpc.supported ? 161 : 62, scanData.gpc.supported ? 105 : 62);
  doc.text(`Status: ${scanData.gpc.supported ? 'Supported' : 'Not Supported'}`, 20, y);
  y += 6;
  doc.setTextColor(74, 85, 104);
  const gpcLines = doc.splitTextToSize(scanData.gpc.details, pageWidth - 40);
  doc.text(gpcLines, 20, y);
  y += gpcLines.length * 5 + 4;

  if (!scanData.gpc.supported) {
    doc.setTextColor(229, 62, 62);
    doc.setFontSize(9);
    const warnLines = doc.splitTextToSize('WARNING: Ignoring GPC requests violates CCPA, CPRA, and multiple state laws (TX, NJ, CT, etc). Fines scale per violation.', pageWidth - 40);
    doc.text(warnLines, 20, y);
    y += warnLines.length * 4 + 6;
  }

  // ── Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // ── Trackers Section
  doc.setFontSize(15);
  doc.setTextColor(45, 55, 72);
  doc.text('Pre-Consent Tracker Audit (GDPR/ePrivacy Risk)', 20, y);
  y += 8;
  doc.setFontSize(11);
  doc.setTextColor(scanData.trackers.found === 0 ? 56 : 221, scanData.trackers.found === 0 ? 161 : 107, scanData.trackers.found === 0 ? 105 : 32);
  doc.text(`Trackers Found Before Consent: ${scanData.trackers.found}`, 20, y);
  y += 6;

  if (scanData.trackers.found > 0) {
    doc.setTextColor(229, 62, 62);
    doc.setFontSize(9);
    const trackerWarn = doc.splitTextToSize('WARNING: Loading marketing/analytics scripts before explicit user consent is a direct violation of GDPR Article 7 and risks fines up to 4% of global revenue.', pageWidth - 40);
    doc.text(trackerWarn, 20, y);
    y += trackerWarn.length * 4 + 4;

    doc.setFontSize(10);
    doc.setTextColor(74, 85, 104);
    scanData.trackers.list.forEach(t => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`• ${t.name} (${t.type})`, 25, y);
      y += 5;
    });
  }
  y += 8;

  // ── Separator
  if (y > 250) { doc.addPage(); y = 20; }
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // ── Security Headers
  doc.setFontSize(15);
  doc.setTextColor(45, 55, 72);
  doc.text('Critical Security Headers', 20, y);
  y += 8;
  doc.setFontSize(11);
  scanData.headers.forEach(h => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setTextColor(h.present ? 56 : 229, h.present ? 161 : 62, h.present ? 105 : 62);
    doc.text(`${h.name}: ${h.present ? '✓ Present' : '✗ Missing'}`, 25, y);
    y += 6;
  });
  y += 8;

  // ── Separator
  if (y > 250) { doc.addPage(); y = 20; }
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // ── Recommended Actions
  doc.setFontSize(14);
  doc.setTextColor(26, 54, 93);
  doc.text('Recommended Actions', 20, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(74, 85, 104);
  doc.text('1. Implement a GPC-compliant consent management platform immediately.', 25, y);
  y += 6;
  doc.text('2. Block all marketing/analytics scripts until active consent is recorded.', 25, y);
  y += 6;
  doc.text('3. Configure missing security headers to prevent XSS and Clickjacking.', 25, y);
  y += 12;

  // ── Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Athan Security — sakis-athan.com', pageWidth / 2, 285, { align: 'center' });

  // Convert to Buffer
  const arrayBuffer = doc.output('arraybuffer');
  return Buffer.from(arrayBuffer);
}
